FROM bitnami/spark:3.3.2-debian-11-r22

USER root

# Use a different Debian mirror (replace with a mirror URL)
RUN echo "deb http://ftp.debian.org/debian/ bullseye main" > /etc/apt/sources.list

# Disable SSL certificate validation
RUN apt-get update --allow-unauthenticated

# Install necessary packages
RUN apt-get install -y --allow-unauthenticated --no-check-certificate gnupg curl gcc python3-dev

# Import GPG key
RUN gpg --keyserver keyserver.ubuntu.com --recv-keys 9D6D8F6BC857C9061A27FAA90C3B3E3A7FA2974B && \
    gpg --export 9D6D8F6BC857C9061A27FAA90C3B3E3A7FA2974B | apt-key add -

# Install additional JAR files
RUN curl https://jdbc.postgresql.org/download/postgresql-42.2.18.jar -o /opt/bitnami/spark/jars/postgresql-42.2.18.jar && \
    curl https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/2.1.1/kafka-clients-2.1.1.jar -o /opt/bitnami/spark/jars/kafka-clients-2.1.1.jar && \
    curl https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.3.2/spark-sql-kafka-0-10_2.12-3.3.2.jar -o /opt/bitnami/spark/jars/spark-sql-kafka-0-10_2.12-3.3.2.jar && \
    curl https://repo1.maven.org/maven2/org/apache/spark/spark-streaming-kafka-0-10_2.12/3.3.2/spark-streaming-kafka-0-10_2.12-3.3.2.jar -o /opt/bitnami/spark/jars/spark-streaming-kafka-0-10_2.12-3.3.2.jar && \
    curl https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.3.2/spark-token-provider-kafka-0-10_2.12-3.3.2.jar -o /opt/bitnami/spark/jars/spark-token-provider-kafka-0-10_2.12-3.3.2.jar && \
    curl https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar -o  /opt/bitnami/spark/jars/commons-pool2-2.11.1.jar

# Install Python packages
RUN pip install \
    lxml \
    requests \
    pandas \
    python-dotenv==0.20.0 \
    kafka-python==2.0.2 \
    faker==18.9.0

# Copy the .env file
COPY ./.env /opt/app/.env
